### ISSUE TITLE
질문있습니다 

### ISSUE THREAD

**Issue by ghost** [0420syj/kw-syllabus#20]
강의 json 파일들 어디서 어떻게 크롤링해서 가져오나요? 자세히 좀 알려주실 수 있을까요?

**Comment by wannysim** [comment]
따로 크롤러를 구현하지 않았습니다.
KLAS 강의계획서 검색시 response로 나오는 데이터를 어플리케이션에 맞는 json 파일로 직접 변형하여 개인 클라우드 스토리지에 업로드하였습니다.
