### ISSUE TITLE
데이터 추가 문의

### ISSUE THREAD

**Issue by Octoping925** [0420syj/kw-syllabus#30]
안녕하세요! 군대 들어가기 전에.. 자주 애용하던 사용자입니다.

하지만 현재(2023년 2학기) 더는 데이터가 올라오지 않는 것으로 보입니다.

서버는 살아있는 것으로 보이는데, 
더는 강의 계획서 데이터를 추가하실 계획이 없으신건가요?

없다면, 제가 데이터를 따로 추가할 방법은 없을까요?

**Comment by wannysim** [comment]
안녕하세요! 😄
우선 관심가져주셔서 감사합니다.

어플리케이션 구조는 크게 아래와 같습니다.
- FE : React SPA (Github Pages로 배포)
- Storage : Oracle Cloud Object storage

먼저 KLAS에서 강의 계획서 검색 response를 제 방식의 json으로 변환하구요. 그걸 Object storage에 업로드 해뒀어요.

그리고 React에서는 Redux를 활용하여, 스토리지 공개 링크에서 json을 받아 검색결과로써 사용하구요.

**Comment by wannysim** [comment]
졸업 이후 KLAS 접근이 불가해, 더 이상 데이터는 올리지 못하고 있어요 😭

혹시라도 이 프로젝트를 clone 받아 개발하시려면, KLAS에서 한 번에 모든 강의계획서를 받아올 방법이 필요해요. 그리고 모든 검색결과 response를 map 함수써서 돌리면서 제가 원하는 새로운 json 객체로 변환했구요.

그리고 S3나 Object storage에 업로드 및 공개 파일로 전환도 필요하구요.

**Comment by wannysim** [comment]
결론만 얘기드리면 위의 이유때문에, 제가 데이터를 추가하는건 불가능합니다 ㅠㅠ

**Comment by Octoping925** [comment]
ㅎㅎ 제가 clone 받아서만들 경우 기존에 저처럼 이 사이트를 쓰시던 분들이 혼란스러우실 것 같아서요

그렇다면 제가 klas의 강의계획서 데이터를 `.json` 파일로 만들어서 주인장님께 전달드리는 방식밖에 없을 것 같군요

**Comment by wannysim** [comment]
죄송하지만 졸업생 입장에서 제가 그거까지 매번 하기는 번거로워서요 😂 2년째 서비스 안 되고 있기 때문에 기존 사용자가 혼란이 있을거라는 생각도 들진 않아요.

이 프로젝트를 fork하시거나, clone 후 새로 repo를 만들어서 서비스 이어가시는 것에 대해서는 환영이지만, 그외에 부분에서 도와드리기는 어렵습니다

**Comment by Octoping925** [comment]
알겠습니다! 번거로우신데 답변주셔서 감사합니다
